In [3]:
import pandas as pd
from processing import SalaryProcessor
df = pd.read_csv('indeed.csv')
SalaryProcessor().process_dataframe(df, 'salary')

,_id,query,title,company,rating_mean,location,summary,sponso,date,rating_count,contract,desc,salary_min,salary_max,salary_mean,salary_original_mode
0,c5bc824b51725453,"[""data+scientist""]",Alternance - Data Scientist H/F,Malakoff Humanis,"3,7",Paris 9e (75),Dans le cadre de votre alternance et en collab...,Sponsorisée,il y a 4 jours,121 avis,"Apprentissage, Contrat pro",Contrat\nALTERNANCE\nFinalité du poste\nAu sei...,0.000000,0.0,0.000000,0.0
1,41984177da7622eb,"[""data+analyst"",""data+scientist""]",DATA ANALYST H/F,Groupement Les Mousquetaires,"3,0",Issy-les-Moulineaux (92),Vous accompagnez la montée en compétences anal...,Sponsorisée,Il y a plus de 30 jours,56 avis,"Temps plein, CDI","ITM Alimentaire International, branche aliment...",0.000000,0.0,0.000000,0.0
2,ecdbb413df0fc6d6,"[""data+scientist""]",Alternance - Data Scientist - Metz (F/H),Banque Populaire Alsace Lorraine Champagne,"3,8",Somme,La Banque Populaire Alsace Lorraine Champagne ...,Sponsorisée,il y a 21 jours,526 avis,"Apprentissage, Contrat pro",La Banque Populaire Alsace Lorraine Champagne ...,0.000000,0.0,0.000000,0.0
3,51c591314452c91c,"[""data+scientist"",""developpeur""]",DATA SCIENTIST / MACHINE LEARNING RESEARCHER I...,Joko,NaN,Paris (75),Tu seras responsable du développement d'algori...,NaN,il y a 4 jours,NaN,Stage,DESCRIPTIF DU POSTE\nTu seras responsable du d...,0.000000,0.0,0.000000,0.0
4,1c8dce698e6095b3,"[""data+scientist""]",Data Scientist - Maintenance prédictive des ap...,MGEN,"3,1",Tours (37),Description de l'établissement ou de la direct...,NaN,il y a 2 jours,194 avis,"Apprentissage, Contrat pro",Description de l'établissement ou de la direct...,0.000000,0.0,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2997,d44dfcd528c42015,"[""developpeur""]",ANALYSTE DÉVELOPPEUR JUNIOR (H/F),Crédit mutuel,"4,0",Strasbourg (67),Les activités de notre Groupe sont importantes...,NaN,Il y a plus de 30 jours,505 avis,CDI,Les activités de notre Groupe sont importantes...,0.000000,0.0,0.000000,0.0
2998,7568ea22f2b4d677,"[""developpeur""]",Développeur PHP H/F,Score & Secure Payment,NaN,Paris (75),"Vous aimez les contextes d'innovation, vous av...",NaN,il y a 7 jours,NaN,"Temps plein, CDI","Vous aimez les contextes d'innovation, vous av...",2916.666667,3750.0,3333.333333,4.0
2999,73802c42e64bdec8,"[""developpeur""]",Graphiste Web Print (Expérimenté),ChoYou,NaN,Paris (75),Tu rejoindras l’équipe du Studio Graphique com...,NaN,Aujourd'hui,NaN,"Temps plein, CDI",Description du poste\nCho You est une agence d...,2027.000000,2477.0,2252.000000,3.0
3000,2f395cc64632fb9a,"[""developpeur""]",Developpeur web Drupal F/H,OPEN WEB ADDICT,NaN,Pantin (93),Développeur drupal 8 f/h ou similaire: 2 ans (...,NaN,il y a 29 jours,NaN,"Temps plein, CDI",Qui sommes-nous ?\nSpécialiste des solutions O...,0.000000,0.0,0.000000,0.0
3001,e019b89bfa767501,"[""developpeur""]",Developpeur .NET / C#,Daveo,NaN,Lyon (69),"NET, vous accompagnerez nos différents clients...",NaN,il y a 4 jours,NaN,CDI,"En tant que Développeur .NET, vous accompagner...",0.000000,0.0,0.000000,0.0